inputSchema:
  type: object
  properties:
    title: real_estate_digital_transformation_application
    pages:
    - id: 1
      name: project_details
      label: Project Details
      hint: null
      type: text
      options: []
      required: false
    - id: 2
      name: lead_contact
      label: Lead Contact
      hint: null
      type: select_one
      options:
      - 'Yes'
      - 'No'
      required: false
    - id: 3
      name: project_budget
      label: Budget
      hint: null
      type: number
      options: []
      required: false
    - id: 4
      name: expected_return
      label: Expected Return
      hint: null
      type: number
      options: []
      required: false
    - id: 5
      name: project_description
      label: Project Description
      hint: null
      type: text
      options: []
      required: false
    - id: 6
      name: business_goals
      label: Business Goals
      hint: null
      type: select_multiple
      options:
      - 'Yes'
      - 'No'
      required: false
    - id: 7
      name: timeline
      label: Timeline
      hint: null
      type: date
      options: []
      required: false
    - id: 8
      name: team_size
      label: Team Size
      hint: null
      type: select_one
      options:
      - 'Yes'
      - 'No'
      required: false
    - id: 9
      name: communication_channels
      label: Communication Channels
      hint: null
      type: select_one
      options:
      - 'Yes'
      - 'No'
      required: false
    - id: 10
      name: project_status
      label: Project Status
      hint: null
      type: select_one
      options:
      - Active
      - Inactive
      required: false
    - id: 11
      name: project_location
      label: Project Location
      hint: null
      type: select_one
      options:
      - 'Yes'
      - 'No'
      required: false
    - id: 12
      name: expected_start_date
      label: Expected Start Date
      hint: null
      type: date
      options: []
      required: false
    - id: 13
      name: expected_end_date
      label: Expected End Date
      hint: null
      type: date
      options: []
      required: false
    - id: 14
      name: project_manager
      label: Project Manager
      hint: null
      type: text
      options: []
      required: false
    - id: 15
      name: team_experience
      label: Team Experience
      hint: null
      type: text
      options: []
      required: false
    - id: 16
      name: team_members
      label: Team Members
      hint: null
      type: text
      options: []
      required: false
    - id: 17
      name: budget_allocation
      label: Budget Allocation
      hint: null
      type: number
      options: []
      required: false
    - id: 18
      name: expected_closeout_date
      label: Expected Closeout Date
      hint: null
      type: date
      options: []
      required: false
    - id: 19
      name: budget_allocated
      label: Budget Allocated
      hint: null
      type: number
      options: []
      required: false
    - id: 20
      name: project_value
      label: Project Value
      hint: null
      type: number
      options: []
      required: false
    - id: 21
      name: expected_closeout_cost
      label: Expected Closeout Cost
      hint: null
      type: number
      options: []
      required: false
    - id: 22
      name: actual_closeout_cost
      label: Actual Closeout Cost
      hint: null
      type: number
      options: []
      required: false
    - id: 23
      name: project_closeout_status
      label: Project Closeout Status
      hint: null
      type: select_one
      options:
      - Active
      - Inactive
      required: false
    - id: 24
      name: project_closeout_date
      label: Project Closeout Date
      hint: null
      type: date
      options: []
      required: false
    - id: 25
      name: closeout_comments
      label: Closeout Comments
      hint: null
      type: text
      options: []
      required: false
