inputSchema:
  type: object
  properties:
    title: Senior Hybrid Hospitality Operations Manager Application Form
    pages:
    - id: 1
      name: first_name
      label: First Name
      hint: null
      type: text
      options: []
      required: false
    - id: 2
      name: last_name
      label: Last Name
      hint: null
      type: text
      options: []
      required: false
    - id: 3
      name: contact_email
      label: Contact Email
      hint: null
      type: email
      options: []
      required: false
    - id: 4
      name: phone_number
      label: Phone Number
      hint: null
      type: text
      options: []
      required: false
    - id: 5
      name: resume_upload
      label: Resume Upload
      hint: null
      type: text
      options: []
      required: false
    - id: 6
      name: job_title
      label: Job Title
      hint: null
      type: text
      options: []
      required: false
    - id: 7
      name: work_experience
      label: Work Experience
      hint: null
      type: text
      options: []
      required: false
    - id: 8
      name: education_background
      label: Education Background
      hint: null
      type: text
      options: []
      required: false
    - id: 9
      name: previous_workplaces
      label: Previous Workplaces
      hint: null
      type: text
      options: []
      required: false
    - id: 10
      name: job_references
      label: Job References
      hint: null
      type: text
      options: []
      required: false
