inputSchema:
  type: object
  properties:
    title: Environmental Literacy Among Students Survey
    pages:
    - id: 1
      name: environmental_literacy
      label: Environmental Literacy
      hint: null
      type: text
      options: []
      required: false
    - id: 2
      name: attitude_towards_environment
      label: attitude_towards_environment
      hint: null
      type: select_one
      options:
      - Label 1
      - Label 2
      - Label 3
      required: false
    - id: 3
      name: environmental_activities
      label: environmental_activities
      hint: null
      type: select_multiple
      options:
      - Option 1
      - Option 2
      - Option 3
      required: false
    - id: 4
      name: environmental_awareness
      label: environmental_awareness
      hint: null
      type: date
      options: []
      required: false
    - id: 5
      name: educational_institutions
      label: educational_institutions
      hint: null
      type: number
      options: []
      required: false
    - id: 6
      name: research_planning
      label: research_planning
      hint: null
      type: text
      options: []
      required: false
    - id: 7
      name: school_environment
      label: school_environment
      hint: null
      type: time
      options: []
      required: false
    - id: 8
      name: program_planning
      label: program_planning
      hint: null
      type: select_one
      options:
      - Option 1
      - Option 2
      - Option 3
      required: false
    - id: 9
      name: survey_completion
      label: survey_completion
      hint: null
      type: note
      options: []
      required: false
