#!/usr/bin/env python3
"""Generate managed meta.yaml files for top-level form content directories."""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass
from datetime import date
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DOCS_INDEX = ROOT / "docs" / "forms-index.json"
GENERATED_AT = date.today().isoformat()
MANAGED_HEADER = "# Generated by scripts/generate_category_meta.py"
IGNORED_DIRS = {
    ".git",
    ".github",
    "__pycache__",
    "categories",
    "docs",
    "guides",
    "scripts",
}
IGNORED_FILE_NAMES = {"meta.yaml", "meta.yml"}


@dataclass(frozen=True)
class IndexSummary:
    generated_at: str | None
    counts_by_category: dict[str, int]
    languages_by_category: dict[str, Counter[str]]


def slugify(value: str) -> str:
    value = value.lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    value = re.sub(r"-{2,}", "-", value).strip("-")
    return value or "category"


def humanize(value: str) -> str:
    return re.sub(r"\s+", " ", value.replace("_", " ")).strip().title()


def collection_type(directory_name: str) -> str:
    for suffix, label in (
        ("_form_templates", "form-templates"),
        ("_templates", "templates"),
        ("_questionnaires", "questionnaires"),
        ("_surveys", "surveys"),
        ("_forms", "forms"),
        ("_camps", "camps"),
    ):
        if directory_name.endswith(suffix):
            return label
    return slugify(directory_name)


def build_description(title: str, kind: str) -> str:
    return f"AI-powered resources and source files for {title.lower()} in the GIC Forms library."


def yaml_value(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def load_index_summary() -> IndexSummary:
    if not DOCS_INDEX.exists():
        return IndexSummary(None, {}, {})

    payload = json.loads(DOCS_INDEX.read_text(encoding="utf-8"))
    forms = payload.get("forms")
    if not isinstance(forms, list):
        return IndexSummary(payload.get("generatedAt"), {}, {})

    counts_by_category: Counter[str] = Counter()
    languages_by_category: dict[str, Counter[str]] = defaultdict(Counter)

    for item in forms:
        if not isinstance(item, dict):
            continue
        category = item.get("category")
        if not isinstance(category, str) or not category:
            continue
        counts_by_category[category] += 1
        language = str(item.get("language") or "en").strip().upper()
        languages_by_category[category][language] += 1

    return IndexSummary(
        payload.get("generatedAt"),
        dict(counts_by_category),
        dict(languages_by_category),
    )


def discover_content_dirs(root: Path) -> list[Path]:
    content_dirs: list[Path] = []
    for path in sorted(root.iterdir()):
        if not path.is_dir():
            continue
        if path.name.startswith(".") or path.name in IGNORED_DIRS:
            continue
        has_form_yaml = any(
            child.is_file()
            and child.name not in IGNORED_FILE_NAMES
            and child.suffix in {".yaml", ".yml"}
            for child in path.iterdir()
        )
        if has_form_yaml:
            content_dirs.append(path)
    return content_dirs


def file_stats(directory: Path) -> dict[str, int]:
    yaml_files = 0
    xlsx_files = 0
    help_files = 0
    for child in directory.iterdir():
        if not child.is_file() or child.name in IGNORED_FILE_NAMES:
            continue
        if child.suffix in {".yaml", ".yml"}:
            yaml_files += 1
        elif child.suffix == ".xlsx":
            xlsx_files += 1
        elif child.name.endswith(".help.md"):
            help_files += 1
    return {
        "yamlFiles": yaml_files,
        "xlsFormFiles": xlsx_files,
        "helpFiles": help_files,
    }


def render_meta(directory: Path, index_summary: IndexSummary) -> str:
    category_id = directory.name
    title = humanize(category_id)
    slug = slugify(category_id)
    kind = collection_type(category_id)
    stats = file_stats(directory)
    stats["indexedForms"] = index_summary.counts_by_category.get(category_id, 0)
    languages = index_summary.languages_by_category.get(category_id, Counter())
    category_page_path = ROOT / "categories" / f"{slug}.html"

    lines = [
        MANAGED_HEADER,
        f"categoryId: {yaml_value(category_id)}",
        f"title: {yaml_value(title)}",
        f"slug: {yaml_value(slug)}",
        f"collectionType: {yaml_value(kind)}",
        f"description: {yaml_value(build_description(title, kind))}",
        f"directory: {yaml_value(category_id)}",
        f"browseUrl: {yaml_value(f'https://forms.gic.mx/browse.html#category={category_id}')}",
    ]
    if category_page_path.exists():
        lines.append(
            f"categoryPage: {yaml_value(f'https://forms.gic.mx/categories/{slug}.html')}"
        )
    lines.extend(
        [
            f"generatedAt: {yaml_value(GENERATED_AT)}",
            f"generatedBy: {yaml_value('scripts/generate_category_meta.py')}",
        ]
    )
    if index_summary.generated_at:
        lines.append(f"formsIndexGeneratedAt: {yaml_value(index_summary.generated_at)}")
    lines.append("stats:")
    for key in ("yamlFiles", "xlsFormFiles", "helpFiles", "indexedForms"):
        lines.append(f"  {key}: {stats[key]}")
    if languages:
        lines.append("languages:")
        for language, count in sorted(languages.items()):
            lines.append(f"  {yaml_value(language)}: {count}")
    else:
        lines.append("languages: {}")
    return "\n".join(lines) + "\n"


def write_or_check(directory: Path, expected: str, *, check: bool) -> tuple[str, Path] | None:
    meta_path = directory / "meta.yaml"
    if meta_path.exists():
        current = meta_path.read_text(encoding="utf-8")
        if not current.startswith(MANAGED_HEADER):
            return ("unmanaged", meta_path)
        if current == expected:
            return None
        if check:
            return ("outdated", meta_path)
    else:
        if check:
            return ("missing", meta_path)

    meta_path.write_text(expected, encoding="utf-8")
    return ("updated", meta_path)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Report missing or outdated generated metadata without writing files.",
    )
    args = parser.parse_args()

    index_summary = load_index_summary()
    content_dirs = discover_content_dirs(ROOT)
    results: Counter[str] = Counter()

    for directory in content_dirs:
        result = write_or_check(
            directory,
            render_meta(directory, index_summary),
            check=args.check,
        )
        if result is None:
            results["unchanged"] += 1
            continue
        status, path = result
        results[status] += 1
        print(f"{status}\t{path.relative_to(ROOT)}")

    print(
        json.dumps(
            {
                "directories": len(content_dirs),
                "unchanged": results["unchanged"],
                "updated": results["updated"],
                "missing": results["missing"],
                "outdated": results["outdated"],
                "unmanaged": results["unmanaged"],
            },
            ensure_ascii=True,
        )
    )

    if args.check and (results["missing"] or results["outdated"] or results["unmanaged"]):
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
