inputSchema:
  type: object
  properties:
    title: Geography And Environment Quiz
    pages:
    - id: 1
      name: geography_and_environment_quiz_form
      label: Geography and Environment Quiz Form
      hint: null
      type: text
      options: []
      required: false
    - id: 2
      name: geography_and_environment_quiz_form_questions_1
      label: Quiz 1
      hint: null
      type: select_one
      options:
      - 'Yes'
      - 'No'
      required: false
    - id: 3
      name: geography_and_environment_quiz_form_questions_2
      label: Quiz 2
      hint: null
      type: select_one
      options:
      - 'Yes'
      - 'No'
      required: false
    - id: 4
      name: geography_and_environment_quiz_form_answers_1
      label: Quiz 1 Answer
      hint: null
      type: text
      options: []
      required: true
    - id: 5
      name: geography_and_environment_quiz_form_answers_2
      label: Quiz 2 Answer
      hint: null
      type: text
      options: []
      required: false
    - id: 6
      name: geography_and_environment_quiz_form_questions_3
      label: Quiz 3
      hint: null
      type: select_one
      options:
      - 'Yes'
      - 'No'
      required: false
    - id: 7
      name: geography_and_environment_quiz_form_answers_3
      label: Quiz 3 Answer
      hint: null
      type: text
      options: []
      required: false
    - id: 8
      name: geography_and_environment_quiz_form_questions_4
      label: Quiz 4
      hint: null
      type: select_one
      options:
      - 'Yes'
      - 'No'
      required: false
    - id: 9
      name: geography_and_environment_quiz_form_answers_4
      label: Quiz 4 Answer
      hint: null
      type: text
      options: []
      required: false
    - id: 10
      name: geography_and_environment_quiz_form_questions_5
      label: Quiz 5
      hint: null
      type: select_one
      options:
      - 'Yes'
      - 'No'
      required: false
    - id: 11
      name: geography_and_environment_quiz_form_answers_5
      label: Quiz 5 Answer
      hint: null
      type: text
      options: []
      required: false
    - id: 12
      name: geography_and_environment_quiz_form_questions_6
      label: Quiz 6
      hint: null
      type: select_one
      options:
      - 'Yes'
      - 'No'
      required: false
    - id: 13
      name: geography_and_environment_quiz_form_answers_6
      label: Quiz 6 Answer
      hint: null
      type: text
      options: []
      required: false
    - id: 14
      name: geography_and_environment_quiz_form_questions_7
      label: Quiz 7
      hint: null
      type: select_one
      options:
      - 'Yes'
      - 'No'
      required: false
    - id: 15
      name: geography_and_environment_quiz_form_answers_7
      label: Quiz 7 Answer
      hint: null
      type: text
      options: []
      required: false
    - id: 16
      name: geography_and_environment_quiz_form_questions_8
      label: Quiz 8
      hint: null
      type: select_one
      options:
      - 'Yes'
      - 'No'
      required: false
    - id: 17
      name: geography_and_environment_quiz_form_answers_8
      label: Quiz 8 Answer
      hint: null
      type: text
      options: []
      required: false
    - id: 18
      name: geography_and_environment_quiz_form_questions_9
      label: Quiz 9
      hint: null
      type: select_one
      options:
      - 'Yes'
      - 'No'
      required: false
    - id: 19
      name: geography_and_environment_quiz_form_answers_9
      label: Quiz 9 Answer
      hint: null
      type: text
      options: []
      required: false
    - id: 20
      name: geography_and_environment_quiz_form_questions_10
      label: Quiz 10
      hint: null
      type: select_one
      options:
      - 'Yes'
      - 'No'
      required: false
    - id: 21
      name: geography_and_environment_quiz_form_answers_10
      label: Quiz 10 Answer
      hint: null
      type: text
      options: []
      required: false
    - id: 22
      name: geography_and_environment_quiz_form_questions_11
      label: Quiz 11
      hint: null
      type: select_one
      options:
      - 'Yes'
      - 'No'
      required: false
    - id: 23
      name: geography_and_environment_quiz_form_answers_11
      label: Quiz 11 Answer
      hint: null
      type: text
      options: []
      required: false
    - id: 24
      name: geography_and_environment_quiz_form_questions_12
      label: Quiz 12
      hint: null
      type: select_one
      options:
      - 'Yes'
      - 'No'
      required: false
    - id: 25
      name: geography_and_environment_quiz_form_answers_12
      label: Quiz 12 Answer
      hint: null
      type: text
      options: []
      required: false
