inputSchema:
  type: object
  properties:
    title: Internal Audit Scope Expansion Application Form
    pages:
    - id: 1
      name: user_id
      label: user-id
      hint: null
      type: number
      options: []
      required: false
    - id: 2
      name: date
      label: date
      hint: null
      type: date
      options: []
      required: false
    - id: 3
      name: time
      label: time
      hint: null
      type: time
      options: []
      required: false
    - id: 4
      name: reason
      label: reason
      hint: null
      type: text
      options: []
      required: false
    - id: 5
      name: description
      label: description
      hint: null
      type: text
      options: []
      required: false
